app = "aerobotics-api"
primary_region = "jnb"  

[build]
  dockerfile = "Dockerfile"

[env]
  WEB_CONCURRENCY = "2"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/ping"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
